### ISSUE TITLE
Not working on serverless v0.5.0

### ISSUE THREAD

**Issue by axelx5** [Nopik/serverless-serve#26]
I update serverless to v0.5.0 and serverless-serve is returning the following error:

```
/Users/axel/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at module.exports.ServerlessPlugin._registerLambdas (/Users/axel/Projects/api_delivery/api/node_modules/serverless-serve/index.js:5:26)
    at Serverless._loadPlugins (/Users/axel/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/Users/axel/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /Users/axel/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/Users/axel/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/Users/axel/.npm-packages/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by andersdn** [comment]
@axelx5  there is a PR waiting to be merged that fixes this, if you need it you can cherry pick PR https://github.com/Nopik/serverless-serve/pull/25 onto your local and wait for it to be approved

**Comment by axelx5** [comment]
@andersdn nice! thank dude!
